### ISSUE TITLE
[Meeting] 03/09/2023

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/Total-Knee-Replacement-Post-Surgical-Assessment#23]
## What
Meeting related to [2023 MIDL](https://2023.midl.io/) short paper
<br>

## TODO
- [x] #24
- [x] Another experiment that mixes pixel loss & geometry loss
- [x] Results should be saved in different labels, and distance should be calculated in average + RMSE
- [x] Box plot + scatter plot of 18 dots per label - show that this model is performing well
- [x] Loss plot - change from heatmap image -> pixel plot image
- [x] Do two different experiments on 60 - 5, 60 - 10, and do other experiments based on the better performing experiment

**Comment by yehyunsuh** [comment]
Box & scatter plot only consists of distance
![IMG_2445](https://user-images.githubusercontent.com/73840274/224376719-f99a23f3-c1b0-4437-9a4c-89a08cca93b0.jpeg)
![IMG_2446](https://user-images.githubusercontent.com/73840274/224376721-bbcbd927-07de-4eb8-86bc-b5caf3990f19.jpeg)

**Comment by yehyunsuh** [comment]
Augmentation in dilation? Currently it is in 45 degrees of square, maybe change the degree?

**Comment by yehyunsuh** [comment]
Chose to not mix pixel loss & geometry loss. Other tasks done. Issue closed.
