### ISSUE TITLE
[Bug] Double Segmentation Issue

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/Total-Knee-Replacement-Post-Surgical-Assessment#29]
## What
Double Segmentation Issue: https://yehyunsuh.notion.site/Double-Segmentation-Issue-330f81de8f55453981fae232fb055ba4
![epoch_299_overlaid](https://user-images.githubusercontent.com/73840274/233683023-a29fcd92-1104-4e52-8dff-7044d55ed217.png)
![epoch_299_overlaid](https://user-images.githubusercontent.com/73840274/233683133-434b4bee-8a79-4ad3-a8a4-a84a3f456d94.png)

## Why
Currently, do not know the reason why

## TODO
- [x] Go through annotation file
- [x] Go through code one more time
- [x] Use `spatial mean` as our loss function

**Comment by yehyunsuh** [comment]
Using spatial mean has not worked. Using angular loss has made the model to be much more stable.
