### ISSUE TITLE
[Meeting] 04/20/2023

### ISSUE THREAD

**Issue by yehyunsuh** [yehyunsuh/Total-Knee-Replacement-Post-Surgical-Assessment#30]
## What
New things to do.

## Why
Extracting 6 point has been successful with mean RMSE < 3.

## TODO - before
- [x] Last layer should output values between -inf ~ inf, rather that 0~1
- [x] Use of non-pretrained models if more data ( or maybe I can just try )
- [x] Visualize the prediction in annotaion-overlaid image

## TODO - now
- [x] Angle Visualization on Test Image
- [x] Experiments so that 3 categories in angle can be < 2
- [x] Graph Visualization given by Dr.Martin

**Comment by yehyunsuh** [comment]
~Unable to do nn.DataParallel() + no sigmoid~ Fixed

**Comment by yehyunsuh** [comment]
How about using RMSE as a loss?
How about calculating the mean of 1s?
